// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AICareerBuddy_Entities.Entities;

public partial class AIR_projektContext : DbContext
{
    public AIR_projektContext()
    {
    }

    public AIR_projektContext(DbContextOptions<AIR_projektContext> options)
        : base(options)
    {
    }

    public virtual DbSet<JobListing> JobListings { get; set; }

    public virtual DbSet<ResumeFileInfo> ResumeFileInfos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=infoguardians.database.windows.net;Initial Catalog=AIR_projekt;Persist Security Info=True;User ID=admin123;Password=Infoguardians123;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<JobListing>(entity =>
        {
            entity.ToTable("JobListing");

            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Location)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Terms).HasColumnType("text");
        });

        modelBuilder.Entity<ResumeFileInfo>(entity =>
        {
            entity.ToTable("ResumeFileInfo");

            entity.HasIndex(e => e.Id, "IX_ResumeFileInfo").IsUnique();

            entity.Property(e => e.Extension)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Path).HasColumnType("text");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}