// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AICareerBuddy_Entities.Entities;

public partial class Employer
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Adress { get; set; }

    public string Occupation { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

    public virtual User User { get; set; }
}