// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AICareerBuddy_Entities.Entities;

public partial class FilesInfo
{
    public string Name { get; set; }

    public string Path { get; set; }

    public long? Size { get; set; }

    public string Extension { get; set; }

    public DateOnly? CreateDate { get; set; }
}