// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AICareerBuddy_Entities.Entities;

public partial class JobApplication
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int JobId { get; set; }

    public DateOnly? DateOfSubmission { get; set; }

    public string Status { get; set; }

    public int? ExpectedPay { get; set; }

    public string WorkExperience { get; set; }

    public int? EmployerId { get; set; }

    public string Education { get; set; }

    public virtual Employer Employer { get; set; }
}