// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AICareerBuddy_Entities.Entities;

public partial class JobListing
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string Location { get; set; }

    public DateOnly? ListingExpires { get; set; }

    public string Terms { get; set; }

    public int? PayPerHour { get; set; }
}