// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AICareerBuddy_Entities.Entities;

public partial class Resume
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string AboutMe { get; set; }

    public string Projects { get; set; }

    public string WorkExperience { get; set; }
}