// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AICareerBuddy_DataAccessLayer.Models;

public partial class AIR_projektContext : DbContext
{
    public AIR_projektContext(DbContextOptions<AIR_projektContext> options)
        : base(options)
    {
    }

    public virtual DbSet<JobListing> JobListings { get; set; }

    public virtual DbSet<ResumeFileInfo> ResumeFileInfos { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<JobListing>(entity =>
        {
            entity.ToTable("JobListing");

            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Location)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Terms).HasColumnType("text");

            entity.HasOne(d => d.Employer).WithMany(p => p.JobListings)
                .HasForeignKey(d => d.EmployerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobListing_User");
        });

        modelBuilder.Entity<ResumeFileInfo>(entity =>
        {
            entity.ToTable("ResumeFileInfo");

            entity.HasIndex(e => e.Id, "IX_ResumeFileInfo").IsUnique();

            entity.Property(e => e.Extension)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Path).HasColumnType("text");

            entity.HasOne(d => d.User).WithMany(p => p.ResumeFileInfos)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResumeFileInfo_User");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}