// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AICareerBuddy_DataAccessLayer.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public virtual ICollection<JobListing> JobListings { get; set; } = new List<JobListing>();

    public virtual ICollection<ResumeFileInfo> ResumeFileInfos { get; set; } = new List<ResumeFileInfo>();
}